/* Drop databases */
DROP DATABASES meets2;

/* Create databases */
CREATE DATABASE `meets2` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

SET SESSION FOREIGN_KEY_CHECKS=0;

DROP TABLE M_BLOOD_TYPE_DATAS;
DROP TABLE M_HAPPY_EPISODE_DATAS;
DROP TABLE M_INCOME_DATAS;
DROP TABLE M_NARROW_AREA_DATAS;
DROP TABLE M_POLICY_DATAS;
DROP TABLE M_PROFILE_DATAS;
DROP TABLE M_SEX_DATAS;
DROP TABLE M_SITE_INFO_DATAS;
DROP TABLE M_TALL_DATAS;
DROP TABLE M_TEMP_REGIST_IMAGE_DATAS;
DROP TABLE M_TEMP_REGSIT_BBS_DATAS;
DROP TABLE M_TYPE_DATAS;
DROP TABLE M_WEIGHT_DATAS;
DROP TABLE M_WIDE_AREA_DATAS;
DROP TABLE T_AUTH_DATAS;

/* Create Tables */

CREATE TABLE M_BLOOD_TYPE_DATAS
(
	ID TINYINT(2) NOT NULL UNIQUE AUTO_INCREMENT,
	NAME VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;


CREATE TABLE M_HAPPY_EPISODE_DATAS
(
	ID INT NOT NULL UNIQUE AUTO_INCREMENT,
	NAME VARCHAR(255),
	SEX INT NOT NULL,
	EPISODE TEXT NOT NULL,
	CREATED_AT DATETIME,
	MODIFIED DATETIME,
	PRIMARY KEY (ID)
);


CREATE TABLE M_INCOME_DATAS
(
	ID INT NOT NULL UNIQUE AUTO_INCREMENT,
	NAME VARCHAR(255) NOT NULL,
	PRIMARY KEY (ID)
);


CREATE TABLE M_NARROW_AREA_DATAS
(
	ID INT NOT NULL UNIQUE AUTO_INCREMENT,
	M_WIDE_AREA_DATA_ID INT NOT NULL UNIQUE,
	NAME VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;


CREATE TABLE M_POLICY_DATAS
(
	ID INT NOT NULL UNIQUE AUTO_INCREMENT,
	POLICY TEXT NOT NULL,
	PRIMARY KEY (ID)
);


CREATE TABLE M_PROFILE_DATAS
(
	ID BIGINT UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
	T_AUTH_DATA_ID BIGINT UNSIGNED NOT NULL,
	M_SEX_DATA_ID INT NOT NULL,
	M_WIDE_AREA_DATA_ID INT NOT NULL,
	M_NARROW_AREA_DATA_ID INT,
	M_TALL_DATA_ID TINYINT(2),
	N_BLOOD_TYPE_DATA_ID TINYINT(2),
	M_WEIGHT_DATA_ID INT,
	M_INCOME_DATA_ID INT,
	M_TYPE_DATA_ID INT,
	COMMENT TEXT CHARACTER SET utf8 COLLATE utf8_general_ci,
	CREATED_AT DATETIME,
	MODIFIED DATETIME,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;


CREATE TABLE M_SEX_DATAS
(
	ID INT NOT NULL UNIQUE AUTO_INCREMENT,
	NAME VARCHAR(255) NOT NULL,
	PRIMARY KEY (ID)
);


CREATE TABLE M_SITE_INFO_DATAS
(
	ID INT NOT NULL UNIQUE AUTO_INCREMENT,
	NAME VARCHAR(0) NOT NULL,
	CREATED_AT DATETIME,
	MODIFIED DATETIME,
	PRIMARY KEY (ID)
);


CREATE TABLE M_TALL_DATAS
(
	ID TINYINT(2) NOT NULL UNIQUE AUTO_INCREMENT,
	NAME VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;


CREATE TABLE M_TEMP_REGIST_IMAGE_DATAS
(
	ID BIGINT NOT NULL UNIQUE AUTO_INCREMENT,
	M_TEMP_REGIST_BBS_DATA_ID INT,
	PATH VARCHAR(255) NOT NULL,
	HIDDEN_FLG INT,
	CREATED_AT DATETIME NOT NULL,
	MODIFIED DATETIME NOT NULL,
	PRIMARY KEY (ID)
);


CREATE TABLE M_TEMP_REGSIT_BBS_DATAS
(
	ID INT NOT NULL UNIQUE AUTO_INCREMENT,
	NAME VARCHAR(255) NOT NULL,
	SEX INT NOT NULL,
	TITLE VARCHAR(255) NOT NULL,
	BBS_COMMENT TEXT NOT NULL,
	CREATED_AT DATETIME NOT NULL,
	MODIFIED DATETIME NOT NULL,
	PRIMARY KEY (ID)
);


CREATE TABLE M_TYPE_DATAS
(
	ID INT NOT NULL UNIQUE AUTO_INCREMENT,
	NAME VARCHAR(255) NOT NULL,
	M_SEX_DATA_ID INT,
	PRIMARY KEY (ID)
);


CREATE TABLE M_WEIGHT_DATAS
(
	ID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(255) NOT NULL,
	PRIMARY KEY (ID)
);


CREATE TABLE M_WIDE_AREA_DATAS
(
	ID INT NOT NULL UNIQUE AUTO_INCREMENT,
	NAME VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;


CREATE TABLE T_AUTH_DATAS
(
	ID BIGINT UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
	PASSWORD VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
	MAIL_ADDRESS VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL UNIQUE,
	NAME VARCHAR(255) NOT NULL,
	TEL_NO INT NOT NULL,
	BIRTH_DAY INT NOT NULL,
	GUID VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL UNIQUE,
	VALID_FLG TINYINT NOT NULL,
	AGE_CHECK_FLG INT,
	TEMP_REGIST_FLG INT,
	CREATED_AT DATETIME,
	MODIFIED DATETIME,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;



/* Create Foreign Keys */

ALTER TABLE M_PROFILE_DATAS
	ADD FOREIGN KEY (N_BLOOD_TYPE_DATA_ID)
	REFERENCES M_BLOOD_TYPE_DATAS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE M_PROFILE_DATAS
	ADD FOREIGN KEY (M_INCOME_DATA_ID)
	REFERENCES M_INCOME_DATAS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE M_PROFILE_DATAS
	ADD FOREIGN KEY (M_NARROW_AREA_DATA_ID)
	REFERENCES M_NARROW_AREA_DATAS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE M_PROFILE_DATAS
	ADD FOREIGN KEY (M_SEX_DATA_ID)
	REFERENCES M_SEX_DATAS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE M_TYPE_DATAS
	ADD FOREIGN KEY (M_SEX_DATA_ID)
	REFERENCES M_SEX_DATAS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE M_PROFILE_DATAS
	ADD FOREIGN KEY (M_TALL_DATA_ID)
	REFERENCES M_TALL_DATAS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE M_TEMP_REGIST_IMAGE_DATAS
	ADD FOREIGN KEY (M_TEMP_REGIST_BBS_DATA_ID)
	REFERENCES M_TEMP_REGSIT_BBS_DATAS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE M_PROFILE_DATAS
	ADD FOREIGN KEY (M_TYPE_DATA_ID)
	REFERENCES M_TYPE_DATAS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE M_PROFILE_DATAS
	ADD FOREIGN KEY (M_WEIGHT_DATA_ID)
	REFERENCES M_WEIGHT_DATAS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE M_NARROW_AREA_DATAS
	ADD FOREIGN KEY (M_WIDE_AREA_DATA_ID)
	REFERENCES M_WIDE_AREA_DATAS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE M_PROFILE_DATAS
	ADD FOREIGN KEY (M_WIDE_AREA_DATA_ID)
	REFERENCES M_WIDE_AREA_DATAS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE M_PROFILE_DATAS
	ADD FOREIGN KEY (T_AUTH_DATA_ID)
	REFERENCES T_AUTH_DATAS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;




